// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: polygon.proto

package polygon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Aggregate_SayHello_FullMethodName = "/polygon.Aggregate/SayHello"
)

// AggregateClient is the client API for Aggregate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregateClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *AggRequest, opts ...grpc.CallOption) (*AggReply, error)
}

type aggregateClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateClient(cc grpc.ClientConnInterface) AggregateClient {
	return &aggregateClient{cc}
}

func (c *aggregateClient) SayHello(ctx context.Context, in *AggRequest, opts ...grpc.CallOption) (*AggReply, error) {
	out := new(AggReply)
	err := c.cc.Invoke(ctx, Aggregate_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateServer is the server API for Aggregate service.
// All implementations must embed UnimplementedAggregateServer
// for forward compatibility
type AggregateServer interface {
	// Sends a greeting
	SayHello(context.Context, *AggRequest) (*AggReply, error)
	mustEmbedUnimplementedAggregateServer()
}

// UnimplementedAggregateServer must be embedded to have forward compatible implementations.
type UnimplementedAggregateServer struct {
}

func (UnimplementedAggregateServer) SayHello(context.Context, *AggRequest) (*AggReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAggregateServer) mustEmbedUnimplementedAggregateServer() {}

// UnsafeAggregateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateServer will
// result in compilation errors.
type UnsafeAggregateServer interface {
	mustEmbedUnimplementedAggregateServer()
}

func RegisterAggregateServer(s grpc.ServiceRegistrar, srv AggregateServer) {
	s.RegisterService(&Aggregate_ServiceDesc, srv)
}

func _Aggregate_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregate_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateServer).SayHello(ctx, req.(*AggRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aggregate_ServiceDesc is the grpc.ServiceDesc for Aggregate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aggregate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "polygon.Aggregate",
	HandlerType: (*AggregateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Aggregate_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "polygon.proto",
}
